name: Auto send daily loving message
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
      run: node ./app.js

name: Auto send daily loving message
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3
      - run: node ./app.js
